# -*- coding: utf-8 -*-
"""TF-IDF implementation .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5S3IPDYldvd_Aq1_zoL82cTsbAPNbSs
"""

import pandas as pd
import math
import re
from collections import defaultdict, Counter

df = pd.read_csv('/content/shopsense_reviews_10k.csv')

reviews = df["review_text"].astype(str).tolist()

def preprocess(text):
  text = text.lower()

  text = re.sub(r'[^a-zA-Z\u0980-\u09FF\s]', '', text)

  tokens = text.split()
  return tokens


docs = [preprocess(review) for review in reviews]

def build_vocab(docs):
    vocab = {}
    index = 0

    for doc in docs:
        for word in doc:
            if word not in vocab:
                vocab[word] = index
                index += 1
    return vocab


vocab = build_vocab(docs)

def compute_tf(docs):
    tf_list = []

    for doc in docs:
      word_count = Counter(doc)
      total_words = len(doc)

      tf = {}
      for word, count in word_count.items():
        tf[word] = count / total_words


      tf_list.append(tf)

    return tf_list


tf_list = compute_tf(docs)

def compute_idf(docs, vocab):
    N = len(docs)
    doc_freq = defaultdict(int)

    for doc in docs:
        unique_words = set(doc)
        for word in unique_words:
            doc_freq[word] += 1

    idf = {}
    for word in vocab:
        df = doc_freq[word]
        idf[word] = math.log(N / (1 + df))

    return idf

idf = compute_idf(docs, vocab)

def compute_tfidf(tf_list, idf, vocab):
    tfidf_matrix = []

    for tf in tf_list:
        row = {}
        for word, tf_val in tf.items():
            row[vocab[word]] = tf_val * idf[word]
        tfidf_matrix.append(row)

    return tfidf_matrix

tfidf_matrix = compute_tfidf(tf_list, idf, vocab)

print("Total Reviews:", len(tfidf_matrix))     # should be 10,000
print("Vocabulary Size:", len(vocab))

print("Sample TF-IDF vector (doc 0):")
print(tfidf_matrix[0])

