# -*- coding: utf-8 -*-
"""TF-IDF implementation .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5S3IPDYldvd_Aq1_zoL82cTsbAPNbSs
"""

import pandas as pd
import math
import re
from collections import defaultdict, Counter

df = pd.read_csv('/content/shopsense_reviews_10k.csv')

reviews = df["review_text"].astype(str).tolist()

def preprocess(text):
  text = text.lower()

  text = re.sub(r'[^a-zA-Z\u0980-\u09FF\s]', '', text)

  tokens = text.split()
  return tokens


docs = [preprocess(review) for review in reviews]

def build_vocab(docs):
    vocab = {}
    index = 0

    for doc in docs:
        for word in doc:
            if word not in vocab:
                vocab[word] = index
                index += 1
    return vocab


vocab = build_vocab(docs)

def compute_tf(docs):
    tf_list = []

    for doc in docs:
      word_count = Counter(doc)
      total_words = len(doc)

      tf = {}
      for word, count in word_count.items():
        tf[word] = count / total_words


      tf_list.append(tf)

    return tf_list


tf_list = compute_tf(docs)

def compute_idf(docs, vocab):
    N = len(docs)
    doc_freq = defaultdict(int)

    for doc in docs:
        unique_words = set(doc)
        for word in unique_words:
            doc_freq[word] += 1

    idf = {}
    for word in vocab:
        df = doc_freq[word]
        idf[word] = math.log(N / (1 + df))

    return idf

idf = compute_idf(docs, vocab)

def compute_tfidf(tf_list, idf, vocab):
    tfidf_matrix = []

    for tf in tf_list:
        row = {}
        for word, tf_val in tf.items():
            row[vocab[word]] = tf_val * idf[word]
        tfidf_matrix.append(row)

    return tfidf_matrix

tfidf_matrix = compute_tfidf(tf_list, idf, vocab)

print("Total Reviews:", len(tfidf_matrix))     
print("Vocabulary Size:", len(vocab))


import re
from collections import Counter
import math

def preprocess(text):
  text = text.lower()
  text = re.sub(r'[^a-zA-Z\u0980-\u09FF\s]', '', text)
  tokens = text.split()
  return tokens

def compute_query_tf_vector(query_tokens):
    word_count = Counter(query_tokens)
    total_words = len(query_tokens)
    tf = {}
    if total_words == 0:
        return tf # Handle empty query
    for word, count in word_count.items():
        tf[word] = count / total_words
    return tf

def compute_query_tfidf_vector(query_tf, idf, vocab):
    query_tfidf = {}
    for word, tf_val in query_tf.items():
        if word in vocab and word in idf: 
            query_tfidf[vocab[word]] = tf_val * idf[word]
    return query_tfidf

def dot_product(vec1, vec2):
    dot_prod = 0
    # Iterate over the smaller vector for efficiency
    if len(vec1) > len(vec2):
        vec1, vec2 = vec2, vec1
    for idx, val in vec1.items():
        if idx in vec2:
            dot_prod += val * vec2[idx]
    return dot_prod

def magnitude(vec):
    mag = 0
    for val in vec.values():
        mag += val ** 2
    return math.sqrt(mag)

def cosine_similarity(vec1, vec2):
    num = dot_product(vec1, vec2)
    den_vec1 = magnitude(vec1)
    den_vec2 = magnitude(vec2)

    if den_vec1 == 0 or den_vec2 == 0:
        return 0.0 
    return num / (den_vec1 * den_vec2)



query = "great product"


processed_query = preprocess(query)

query_tf = compute_query_tf_vector(processed_query)
query_tfidf_vec = compute_query_tfidf_vector(query_tf, idf, vocab)


similarities = []
for i, doc_tfidf_vec in enumerate(tfidf_matrix):
    sim = cosine_similarity(query_tfidf_vec, doc_tfidf_vec)
    similarities.append((sim, i))


similarities.sort(key=lambda x: x[0], reverse=True)
top_5_reviews_indices = [idx for sim, idx in similarities[:5]]

print(f"Top 5 most relevant reviews for query: '{query}'\n")
for i, idx in enumerate(top_5_reviews_indices):
    original_review = reviews[idx]
    similarity_score = similarities[i][0]
    print(f"Rank {i+1} (Similarity: {similarity_score:.4f}):\n{original_review}\n---\n")

print("Sample TF-IDF vector (doc 0):")
print(tfidf_matrix[0])


from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np


corpus_for_sklearn = [" ".join(doc) for doc in docs]


sklearn_vectorizer = TfidfVectorizer(vocabulary={word: idx for word, idx in vocab.items()})
sklearn_tfidf_matrix = sklearn_vectorizer.fit_transform(corpus_for_sklearn)


sklearn_vocab = sklearn_vectorizer.vocabulary_

custom_tfidf_sparse_matrix = np.zeros(sklearn_tfidf_matrix.shape)

for doc_idx, doc_vec_dict in enumerate(tfidf_matrix):
    for word_idx, tfidf_val in doc_vec_dict.items():

        custom_tfidf_sparse_matrix[doc_idx, word_idx] = tfidf_val

l2_diff = np.linalg.norm(custom_tfidf_sparse_matrix - sklearn_tfidf_matrix.toarray(), axis=1)
avg_l2_diff = np.mean(l2_diff)

print(f"Average L2 difference between custom TF-IDF and sklearn's TF-IDF: {avg_l2_diff:.4f}")

from collections import defaultdict


electronics_reviews_indices = df[df['category'] == 'Electronics'].index.tolist()
electronics_docs = [docs[i] for i in electronics_reviews_indices]
electronics_tf_list = [tf_list[i] for i in electronics_reviews_indices]


electronics_tfidf_matrix = compute_tfidf(electronics_tf_list, idf, vocab)

word_tfidf_sums = defaultdict(float)
word_counts_in_electronics = defaultdict(int)

for doc_tfidf_vec in electronics_tfidf_matrix:
    for vocab_idx, tfidf_val in doc_tfidf_vec.items():
 
        word = next(key for key, value in vocab.items() if value == vocab_idx)
        word_tfidf_sums[word] += tfidf_val
        word_counts_in_electronics[word] += 1

average_tfidf_scores = {}
for word, tfidf_sum in word_tfidf_sums.items():
    if word_counts_in_electronics[word] > 0:
        average_tfidf_scores[word] = tfidf_sum / word_counts_in_electronics[word]

if average_tfidf_scores:
    highest_avg_tfidf_word = max(average_tfidf_scores, key=average_tfidf_scores.get)
    highest_avg_tfidf_score = average_tfidf_scores[highest_avg_tfidf_word]

    print(f"The single word with the highest average TF-IDF score in the 'Electronics' category is: '{highest_avg_tfidf_word}' (Average TF-IDF: {highest_avg_tfidf_score:.4f})\n")

    
    tf_score = 0
    doc_freq_count = 0
    total_docs_in_electronics = len(electronics_docs)
    for doc_tf in electronics_tf_list:
        if highest_avg_tfidf_word in doc_tf:
            tf_score += doc_tf[highest_avg_tfidf_word]
            doc_freq_count += 1

    
    print("Explanation:")
    print(f"  The word '{highest_avg_tfidf_word}' has a high TF-IDF score for the following reasons:")
    print(f"  - Term Frequency (TF): It appears frequently within specific 'Electronics' reviews (contributing to a higher average TF).")
    if highest_avg_tfidf_word in idf:
        print(f"  - Inverse Document Frequency (IDF): Its IDF value is {idf[highest_avg_tfidf_word]:.4f}. A higher IDF suggests that the word is relatively rare across the entire corpus of reviews, making it more distinctive to the documents where it does appear.")
        print("  Therefore, this word is likely a good indicator of topics or specific features discussed prominently in 'Electronics' reviews, but not universally across all product categories.")
    else:
        print(f"  - Inverse Document Frequency (IDF): The word '{highest_avg_tfidf_word}' was not found in the global IDF dictionary, which might indicate it's very specific to a small subset of documents or a new word.")
else:
    print("No words found in 'Electronics' category to calculate average TF-IDF scores.")


import numpy as np

def compute_bm25(docs, query_tokens, k1=1.5, b=0.75):
    N = len(docs)
    avgdl = np.mean([len(doc) for doc in docs])
    doc_freqs = Counter()
    for doc in docs:
        doc_freqs.update(set(doc))
    
    scores = []
    for doc in docs:
        score = 0.0
        doc_len = len(doc)
        tf_counts = Counter(doc)
        for token in query_tokens:
            if token in doc_freqs:
                # IDF calculation for BM25
                df = doc_freqs[token]
                idf = math.log((N - df + 0.5) / (df + 0.5) + 1.0)
                # TF component with saturation and length normalization
                f = tf_counts[token]
                tf_comp = (f * (k1 + 1)) / (f + k1 * (1 - b + b * (doc_len / avgdl)))
                score += idf * tf_comp
        scores.append(score)
    return scores

bm25_scores = compute_bm25(docs, processed_query)
bm25_ranking = sorted(enumerate(bm25_scores), key=lambda x: x[1], reverse=True)[:5]

print("Top 5 Reviews (BM25 Weighting):")
for idx, score in bm25_ranking:
    print(f"Score {score:.4f}: {reviews[idx]}")
